# Add Boost.PFR (header-only, so just find Boost and add include)
find_package(Boost)
if(Boost_FOUND)
    message(STATUS "Boost found: ${Boost_INCLUDE_DIRS}")
    include_directories(${Boost_INCLUDE_DIRS})
else()
    message(STATUS "Use boost prf from folder in repo ${CMAKE_SOURCE_DIR}/src")
    include_directories(${CMAKE_SOURCE_DIR}/src)
endif()