# Pre-populated names for AMD PM Table 0x400005
# Use the "Chess Index" (e.g., A0, H32) as the key.

[names]
A0 = "STAPM Limit"
B0 = "STAPM Value"
C0 = "PPT Limit (Fast)"
D0 = "PPT Value (Fast)"
E0 = "PPT Limit"
F0 = "PPT Value"
G0 = "PPT Limit (APU)"
H0 = "PPT Value (APU)"
A1 = "TDC Limit"
B1 = "TDC Value"
C1 = "TDC Limit (SoC)"
D1 = "TDC Value (SoC)"
E1 = "EDC Limit"
F1 = "EDC Value"
A2 = "THM Limit"
B2 = "THM Value"
C3 = "FIT Limit"
D3 = "FIT Value"
E3 = "VID Limit"
F3 = "VID Value"
C4 = "VDDCR_CPU Power"
D4 = "VDDCR_SOC Power"
G4 = "Socket Power"
H49 = "GFX Voltage"
A50 = "SoC Temperature"
C50 = "GFX Frequency"
E50 = "GFX Busy"
B51 = "FCLK"
C51 = "UCLK"
D51 = "MEMCLK"
D52 = "FCLK Effective"
E71 = "Peak Core Temperature"
F71 = "Peak Core Voltage"
G71 = "Average Core Count"
H71 = "Max SoC Voltage"
C72 = "PROCHOT"
A25 = "Core 0 Power"
B25 = "Core 1 Power"
C25 = "Core 2 Power"
D25 = "Core 3 Power"
E25 = "Core 4 Power"
F25 = "Core 5 Power"
G25 = "Core 6 Power"
H25 = "Core 7 Power"
A26 = "Core 0 Voltage"
B26 = "Core 1 Voltage"
C26 = "Core 2 Voltage"
D26 = "Core 3 Voltage"
E26 = "Core 4 Voltage"
F26 = "Core 5 Voltage"
G26 = "Core 6 Voltage"
H26 = "Core 7 Voltage"
A27 = "Core 0 Temp"
B27 = "Core 1 Temp"
C27 = "Core 2 Temp"
D27 = "Core 3 Temp"
E27 = "Core 4 Temp"
F27 = "Core 5 Temp"
G27 = "Core 6 Temp"
H27 = "Core 7 Temp"
A30 = "Core 0 Clock"
B30 = "Core 1 Clock"
C30 = "Core 2 Clock"
D30 = "Core 3 Clock"
E30 = "Core 4 Clock"
F30 = "Core 5 Clock"
G30 = "Core 6 Clock"
H30 = "Core 7 Clock"
A31 = "Core 0 Effective Clock"
B31 = "Core 1 Effective Clock"
C31 = "Core 2 Effective Clock"
D31 = "Core 3 Effective Clock"
E31 = "Core 4 Effective Clock"
F31 = "Core 5 Effective Clock"
G31 = "Core 6 Effective Clock"
H31 = "Core 7 Effective Clock"
A32 = "Core 0 C0 Residency"
B32 = "Core 1 C0 Residency"
C32 = "Core 2 C0 Residency"
D32 = "Core 3 C0 Residency"
E32 = "Core 4 C0 Residency"
F32 = "Core 5 C0 Residency"
G32 = "Core 6 C0 Residency"
H32 = "Core 7 C0 Residency"
A33 = "Core 0 CC1 Residency"
B33 = "Core 1 CC1 Residency"
C33 = "Core 2 CC1 Residency"
D33 = "Core 3 CC1 Residency"
E33 = "Core 4 CC1 Residency"
F33 = "Core 5 CC1 Residency"
G33 = "Core 6 CC1 Residency"
H33 = "Core 7 CC1 Residency"
A34 = "Core 0 CC6 Residency"
B34 = "Core 1 CC6 Residency"
C34 = "Core 2 CC6 Residency"
D34 = "Core 3 CC6 Residency"
E34 = "Core 4 CC6 Residency"
F34 = "Core 5 CC6 Residency"
G34 = "Core 6 CC6 Residency"
H34 = "Core 7 CC6 Residency"