# Pre-populated names for AMD PM Table 0x400005
# Use the decimal index as the key.

[names]
0 = "STAPM Limit"
1 = "STAPM Value"
2 = "PPT Limit (Fast)"
3 = "PPT Value (Fast)"
4 = "PPT Limit"
5 = "PPT Value"
6 = "PPT Limit (APU)"
7 = "PPT Value (APU)"
8 = "TDC Limit"
9 = "TDC Value"
10 = "TDC Limit (SoC)"
11 = "TDC Value (SoC)"
12 = "EDC Limit"
13 = "EDC Value"
16 = "THM Limit"
17 = "THM Value"
26 = "FIT Limit"
27 = "FIT Value"
28 = "VID Limit"
29 = "VID Value"
34 = "VDDCR_CPU Power"
35 = "VDDCR_SOC Power"
38 = "Socket Power"
200 = "Core 0 Power"
201 = "Core 1 Power"
202 = "Core 2 Power"
203 = "Core 3 Power"
204 = "Core 4 Power"
205 = "Core 5 Power"
206 = "Core 6 Power"
207 = "Core 7 Power"
208 = "Core 0 Voltage"
209 = "Core 1 Voltage"
210 = "Core 2 Voltage"
211 = "Core 3 Voltage"
212 = "Core 4 Voltage"
213 = "Core 5 Voltage"
214 = "Core 6 Voltage"
215 = "Core 7 Voltage"
216 = "Core 0 Temp"
217 = "Core 1 Temp"
218 = "Core 2 Temp"
219 = "Core 3 Temp"
220 = "Core 4 Temp"
221 = "Core 5 Temp"
222 = "Core 6 Temp"
223 = "Core 7 Temp"
240 = "Core 0 Clock"
241 = "Core 1 Clock"
242 = "Core 2 Clock"
243 = "Core 3 Clock"
244 = "Core 4 Clock"
245 = "Core 5 Clock"
246 = "Core 6 Clock"
247 = "Core 7 Clock"
248 = "Core 0 Effective Clock"
249 = "Core 1 Effective Clock"
250 = "Core 2 Effective Clock"
251 = "Core 3 Effective Clock"
252 = "Core 4 Effective Clock"
253 = "Core 5 Effective Clock"
254 = "Core 6 Effective Clock"
255 = "Core 7 Effective Clock"
256 = "Core 0 C0 Residency"
257 = "Core 1 C0 Residency"
258 = "Core 2 C0 Residency"
259 = "Core 3 C0 Residency"
260 = "Core 4 C0 Residency"
261 = "Core 5 C0 Residency"
262 = "Core 6 C0 Residency"
263 = "Core 7 C0 Residency"
264 = "Core 0 CC1 Residency"
265 = "Core 1 CC1 Residency"
266 = "Core 2 CC1 Residency"
267 = "Core 3 CC1 Residency"
268 = "Core 4 CC1 Residency"
269 = "Core 5 CC1 Residency"
270 = "Core 6 CC1 Residency"
271 = "Core 7 CC1 Residency"
272 = "Core 0 CC6 Residency"
273 = "Core 1 CC6 Residency"
274 = "Core 2 CC6 Residency"
275 = "Core 3 CC6 Residency"
276 = "Core 4 CC6 Residency"
277 = "Core 5 CC6 Residency"
278 = "Core 6 CC6 Residency"
279 = "Core 7 CC6 Residency"
399 = "GFX Voltage"
400 = "SoC Temperature"
402 = "GFX Frequency"
404 = "GFX Busy"
409 = "FCLK"
410 = "UCLK"
411 = "MEMCLK"
419 = "FCLK Effective"
572 = "Peak Core Temperature"
573 = "Peak Core Voltage"
574 = "Average Core Count"
575 = "Max SoC Voltage"
578 = "PROCHOT"