# Pre-populated names for AMD PM Table 0x400005
# Use the "Chess Index" (e.g., A0, H32) as the key.

[names]
C0 = "Core 0 Clock"
D0 = "Core 1 Clock"
E0 = "Core 2 Clock"
F0 = "Core 3 Clock"
G0 = "Core 4 Clock"
H0 = "Core 5 Clock"
A1 = "Core 6 Clock"
B1 = "Core 7 Clock"
C2 = "Core 0 Power"
D2 = "Core 1 Power"
E2 = "Core 2 Power"
F2 = "Core 3 Power"
G2 = "Core 4 Power"
H2 = "Core 5 Power"
A3 = "Core 6 Power"
B3 = "Core 7 Power"
C4 = "Core 0 Temp"
D4 = "Core 1 Temp"
E4 = "Core 2 Temp"
F4 = "Core 3 Temp"
G4 = "Core 4 Temp"
H4 = "Core 5 Temp"
A5 = "Core 6 Temp"
B5 = "Core 7 Temp"
C6 = "Core 0 Voltage"
D6 = "Core 1 Voltage"
E6 = "Core 2 Voltage"
F6 = "Core 3 Voltage"
G6 = "Core 4 Voltage"
H6 = "Core 5 Voltage"
A7 = "Core 6 Voltage"
B7 = "Core 7 Voltage"
C8 = "Core 0 Effective Clock"
D8 = "Core 1 Effective Clock"
E8 = "Core 2 Effective Clock"
F8 = "Core 3 Effective Clock"
G8 = "Core 4 Effective Clock"
H8 = "Core 5 Effective Clock"
A9 = "Core 6 Effective Clock"
B9 = "Core 7 Effective Clock"
E16 = "FCLK"
F16 = "FCLK Effective"
G16 = "UCLK"
H16 = "MEMCLK"
C26 = "VDDCR_CPU Power"
D26 = "VDDCR_SOC Power"
F26 = "Socket Power"
G26 = "Package Power"
G28 = "SoC Temperature"
H28 = "Peak Core Temperature"
C30 = "Peak Core Voltage"
D30 = "Max SoC Voltage"
E32 = "STAPM Limit"
F32 = "STAPM Value"
G32 = "PPT Limit"
H32 = "PPT Value"
A33 = "PPT Limit (Fast)"
B33 = "PPT Value (Fast)"
E33 = "TDC Limit"
F33 = "TDC Value"
G33 = "EDC Limit"
H33 = "EDC Value"
A34 = "TDC Limit (SoC)"
B34 = "TDC Value (SoC)"
E34 = "THM Limit"
F34 = "THM Value"
G34 = "FIT Limit"
H34 = "FIT Value"
A35 = "PPT Limit (APU)"
B35 = "PPT Value (APU)"